In [4]:
import numpy as np
from scipy.linalg import lu

### Solve the following system of equations using LU Decomposition method:
#### Find L and U by hand.
#### Confirm that A=LU then solve.
- Ex1. 𝟐𝒙+𝟓𝒚=𝟐𝟏, 𝒙+𝟐𝒚=𝟖.
- Ex2. 𝒙𝟏+𝒙𝟐+𝒙𝟑=𝟏, 𝟒𝒙𝟏+𝟑𝒙𝟐−𝒙𝟑=𝟔, 𝟑𝒙𝟏+𝟓𝒙_𝟐+𝟑𝒙𝟑=𝟒

#### Use scipy.linalg.lu() to slove the previous system using LU decomposition and compare the results.

### Note (when using scipy):
- In the second system of equations We can see the <b>L and U</b> we get are different from the ones we got by hand. 
- You will also see there is a permutation matrix <b>P</b> that returned by the <b>lu function</b>. 
- This permutation matrix record how do we change the order of the equations for easier calculation purposes (for example, if first element in first row is zero, it can not be the pivot equation, since you can not turn the first elements in other rows to zero. Therefore, we need to switch the order of the equations to get a new pivot equation). 
- If you multiply <b>P with A</b>, you will see that this permutation matrix effect.
- You will need to arrange the ouput based on the new matrix <b>A</b> achieved by <b>LU</b> multiplication in order to correctly solve the system of equations.

A = [[2 5]
 [1 2]]
LU =  [[2. 5.]
 [1. 2.]]
M = [[21. ]
 [-2.5]]
x = [[-2.]
 [ 5.]]


P:
 [[1. 0.]
 [0. 1.]]
L:
 [[1.  0. ]
 [0.5 1. ]]
U:
 [[ 2.   5. ]
 [ 0.  -0.5]]


A = [[2 5]
 [1 2]]
LU =  [[2. 5.]
 [1. 2.]]
M = [[21. ]
 [-2.5]]
x = [[-2.]
 [ 5.]]


A = [[ 1  1  1]
 [ 4  3 -1]
 [ 3  5  3]]
LU =  [[ 1  1  1]
 [ 4  3 -1]
 [ 3  5  3]]
M = [[1.]
 [2.]
 [5.]]
x = [[ 1. ]
 [ 0.5]
 [-0.5]]


P:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
L:
 [[1.         0.         0.        ]
 [0.75       1.         0.        ]
 [0.25       0.09090909 1.        ]]
U:
 [[ 4.          3.         -1.        ]
 [ 0.          2.75        3.75      ]
 [ 0.          0.          0.90909091]]
LU:
 [[ 4.  3. -1.]
 [ 3.  5.  3.]
 [ 1.  1.  1.]]
A:
 [[ 1  1  1]
 [ 4  3 -1]
 [ 3  5  3]]


M = [[ 6.        ]
 [-0.5       ]
 [-0.45454545]]
x = [[ 1. ]
 [ 0.5]
 [-0.5]]


### Apply the Jacobi and Gauss-Seidel method to solve
- 𝟓𝒙𝟏−𝟐𝒙𝟐+𝟑𝒙𝟑=−𝟏, −𝟑𝒙𝟏+𝟗𝒙𝟐+𝒙𝟑=𝟐, 𝟐𝒙𝟏−𝒙𝟐−𝟕𝒙𝟑=𝟑
- Solve once without vectorization then use vectorize implementation.
- Check for convergance.
- Use different tolerence and see the difference between the two methods. e.g. tol: 0.01,0.001,0.0001 ... etc.

In [23]:
A = np.array([[5, -2, 3],
     [-3, 9, 1],
     [2, -1, -7]])



diagonal    : [5 9 7]
off diagonal: [5 4 3]
matrix is diagonally dominant


In [18]:
## Jacobi Not Vectorized
epsilon = 0.00001

Iteration results
 k,    x1,    x2,    x3 
1, -0.2000, 0.2222, -0.4286
2, 0.1460, 0.2032, -0.5175
3, 0.1917, 0.3284, -0.4159
4, 0.1809, 0.3323, -0.4207
5, 0.1854, 0.3293, -0.4244
6, 0.1863, 0.3312, -0.4226
7, 0.1861, 0.3313, -0.4226
8, 0.1861, 0.3312, -0.4227
9, 0.1861, 0.3312, -0.4227
10, 0.1861, 0.3312, -0.4227
Converged!


In [19]:
## Gauss-Seidel Not Vectorized
epsilon = 0.00001

Iteration results
 k,    x1,    x2,    x3 
1, -0.2000, 0.1556, -0.5079
2, 0.1670, 0.3343, -0.4286
3, 0.1909, 0.3335, -0.4217
4, 0.1864, 0.3312, -0.4226
5, 0.1861, 0.3312, -0.4227
6, 0.1861, 0.3312, -0.4227
7, 0.1861, 0.3312, -0.4227
Converged!


In [20]:
## Jacobi Vectorized
epsilon = 0.00001


spectral radius : 0.26739980828320886
Iteration results
 k,    x1,    x2,    x3 
1, -0.2000, 0.2222, -0.4286
2, 0.1460, 0.2032, -0.5175
3, 0.1917, 0.3284, -0.4159
4, 0.1809, 0.3323, -0.4207
5, 0.1854, 0.3293, -0.4244
6, 0.1863, 0.3312, -0.4226
7, 0.1861, 0.3313, -0.4226
8, 0.1861, 0.3312, -0.4227
9, 0.1861, 0.3312, -0.4227
10, 0.1861, 0.3312, -0.4227
Converged!


In [21]:
## Gauss-Seidel Vectorized
epsilon = 0.00001


spectral radius : 0.11268723396380219
Iteration results
 k,    x1,    x2,    x3 
1, -0.2000, 0.1556, -0.5079
2, 0.1670, 0.3343, -0.4286
3, 0.1909, 0.3335, -0.4217
4, 0.1864, 0.3312, -0.4226
5, 0.1861, 0.3312, -0.4227
6, 0.1861, 0.3312, -0.4227
7, 0.1861, 0.3312, -0.4227
Converged!


### Use np.linalg.solve() to solve the previous system and compare the results.

array([[ 0.18611987],
       [ 0.33123028],
       [-0.42271293]])

### Use scipy.linalg.lu() to slove the previous system using LU decomposition and compare the results.

In [105]:
P

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [106]:
L

array([[ 1.        ,  0.        ,  0.        ],
       [-0.6       ,  1.        ,  0.        ],
       [ 0.4       , -0.02564103,  1.        ]])

In [107]:
U

array([[ 5.        , -2.        ,  3.        ],
       [ 0.        ,  7.8       ,  2.8       ],
       [ 0.        ,  0.        , -8.12820513]])

A = [[ 5 -2  3]
 [-3  9  1]
 [ 2 -1 -7]]
LU =  [[ 5. -2.  3.]
 [-3.  9.  1.]
 [ 2. -1. -7.]]
M = [[-1.        ]
 [ 1.4       ]
 [ 3.43589744]]

Solution: 
x = [[ 0.1861206 ]
 [ 0.33123065]
 [-0.42271278]]
